### PR TITLE
add styling and buttons to profile page

### PR DESCRIPTION
**Pull request by danielrsilver**
Helper viewing someone else's page
screen shot 2018-10-15 at 1 09 54 am

### CODE REVIEW

**Comment by danielrsilver** [comment]
MOVER viewing their own page
screen shot 2018-10-15 at 1 09 11 am

**Comment by danielrsilver** [comment]
Star rating, mover rating, and total rating are hard coded at the moment.

**Comment by danielrsilver** [comment]
need to convert date to a normal readable string and fix the picture so that it crops rather than stretching

**Comment by danielrsilver** [comment]
added icon next to header
screen shot 2018-10-15 at 2 14 52 am

**Comment by vpio** [comment]
awesome

**Pull request merged**
